global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'ecs-prometheus-server'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093 # FIXME

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exprter'
    dns_sd_configs:
      - names:
        - node-exporter.ex-aws-servicediscovery.ecs-service-discovery.local

  - job_name: 'example-worker'
    dns_sd_configs:
      - names:
        - example-worker.ex-aws-servicediscovery.ecs-service-discovery.local
